name: flutter_ameno_ipsum
description: Lorem Ipsum but it's Ameno from Era. Generate placeholder texts easily. Dorime
version: 1.0.0
homepage: https://github.com/ndelanou/flutter_ameno_ipsum

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: